[package]
name = "parley"
version = "0.6.0"
description = "Parley provides an API for implementing rich text layout."
keywords = ["text", "layout"]
categories = ["gui", "graphics"]
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
exclude = ["/tests"]

[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true

[features]
default = ["system"]
std = ["fontique/std", "harfrust/std", "peniko/std", "skrifa/std", "swash/std"]
libm = ["fontique/libm", "peniko/libm", "skrifa/libm", "swash/libm", "dep:core_maths"]
# Enables support for system font backends
system = ["std", "fontique/system"]
accesskit = ["dep:accesskit"]

[dependencies]
swash = { workspace = true }
skrifa = { workspace = true }
linebender_resource_handle = { workspace = true }
fontique = { workspace = true }
core_maths = { version = "0.1.1", optional = true }
accesskit = { workspace = true, optional = true }
hashbrown = { workspace = true }
harfrust = { workspace = true }
icu_collections = { workspace = true }
# Used in ICU4X baked data sources, which depend on compiled data, but just locale fallback rules.
icu_locale = { workspace = true }
icu_normalizer = { workspace = true }
icu_properties = { workspace = true, features = ["unicode_bidi"] }
icu_provider = { workspace = true }
icu_segmenter = { workspace = true, features = ["auto"] }
unicode-bidi = { workspace = true }
# Used in ICU4X baked data sources
zerovec = { workspace = true }

[build-dependencies]
icu_normalizer = { workspace = true }
icu_properties = { workspace = true }
icu_provider_export = { workspace = true }
icu_provider_source = { workspace = true }
icu_segmenter = { workspace = true }

[dev-dependencies]
parley_dev = { workspace = true }
peniko = { workspace = true }
tiny-skia = "0.11.4"
