[package]
name = "unicode_data"
keywords = ["text", "layout"]
categories = ["gui", "graphics"]
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[features]
default = ["build"]
build = [
    "icu_provider_source",
    "icu_codepointtrie_builder",
    "icu_provider_export",
    "icu_normalizer",
    "icu_segmenter",
    "icu_provider_adapters",
]

[dependencies]
icu = { version = "2", features = ["datagen"] }
icu_properties = { version = "2", features = ["datagen"] }
icu_collections = { version = "2", features = ["databake", "serde"] }
icu_provider = { workspace = true }
icu_provider_source = { workspace = true, optional = true }
yoke = { version = "0.8", features = ["derive"] }
zerofrom = "0.1"
unicode-bidi = { workspace = true, features = ["smallvec"] }
icu_normalizer = { workspace = true, optional = true }
icu_segmenter = { workspace = true, optional = true }
icu_provider_export = { version = "2", features = [
    "baked_exporter",
    "blob_exporter",
], optional = true }
serde = { version = "1", features = ["derive"] }
databake = { version = "0.2", features = ["derive"] }
icu_codepointtrie_builder = { version = "0.5.0", features = ["wasm"], optional = true }
icu_provider_adapters = { version = "2.0.0", features = ["export"], optional = true }

[lints]
workspace = true
